# Generated by Django 4.2.7 on 2025-12-06 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_data', '0003_studentprofile_domicile_upload_and_more'),
        ('ai_mapping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldmapping',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_data.studentprofile'),
        ),
    ]
