# Generated by Django 4.2.7 on 2025-12-05 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('student_cnic', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('nationality', models.CharField(max_length=100)),
                ('religion', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('domicile', models.CharField(max_length=100)),
                ('hafiz_quran', models.BooleanField(default=False)),
                ('hostel', models.BooleanField(default=False)),
                ('father_income', models.IntegerField()),
                ('father_name', models.CharField(max_length=255)),
                ('father_cnic', models.CharField(max_length=20)),
                ('father_phone', models.CharField(max_length=20)),
                ('mother_name', models.CharField(max_length=255)),
                ('guardian_name', models.CharField(max_length=255)),
                ('guardian_mobile', models.CharField(max_length=20)),
                ('guardian_cnic', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
