# Generated by Django 4.2.7 on 2025-12-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_data', '0002_studentprofile_board_studentprofile_inter_part_one_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='domicile_upload',
            field=models.FileField(blank=True, null=True, upload_to='documents/domicile/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='inter_degree',
            field=models.FileField(blank=True, null=True, upload_to='documents/inter/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='matric_degree',
            field=models.FileField(blank=True, null=True, upload_to='documents/matric/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
