# Generated by Django 4.2.7 on 2025-12-14 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('university_type', models.CharField(choices=[('public', 'Public University'), ('private', 'Private University')], max_length=50)),
                ('website', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('fee_range', models.CharField(blank=True, choices=[('low', 'Low (Under 50,000 PKR per semester)'), ('medium', 'Medium (50,000 - 150,000 PKR per semester)'), ('high', 'High (150,000 - 300,000 PKR per semester)'), ('very_high', 'Very High (Above 300,000 PKR per semester)')], max_length=50)),
                ('programs_offered', models.JSONField(blank=True, default=list, help_text='List of programs/fields offered')),
                ('achievements', models.TextField(blank=True, help_text='Notable achievements and rankings')),
                ('facilities', models.JSONField(blank=True, default=list, help_text='Available facilities')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('current_city', models.CharField(help_text='Current city of residence', max_length=100)),
                ('current_province', models.CharField(help_text='Current province', max_length=100)),
                ('can_move_to_other_cities', models.BooleanField(default=False, help_text='Can the user move to other cities?')),
                ('preferred_cities', models.JSONField(blank=True, default=list, help_text='List of preferred cities if can move')),
                ('interests', models.JSONField(default=list, help_text='List of academic interests/subjects')),
                ('preferred_field_of_study', models.CharField(blank=True, help_text='Preferred field of study', max_length=200)),
                ('academic_level', models.CharField(choices=[('high_school', 'High School'), ('intermediate', 'Intermediate/FSC'), ('bachelor', 'Bachelor'), ('master', 'Master'), ('phd', 'PhD')], default='intermediate', max_length=50)),
                ('current_gpa', models.FloatField(blank=True, help_text='Current GPA/CGPA', null=True)),
                ('fee_affordability', models.CharField(choices=[('low', 'Low (Under 50,000 PKR per semester)'), ('medium', 'Medium (50,000 - 150,000 PKR per semester)'), ('high', 'High (150,000 - 300,000 PKR per semester)'), ('very_high', 'Very High (Above 300,000 PKR per semester)')], help_text='Fee affordability range', max_length=50)),
                ('scholarship_required', models.BooleanField(default=False, help_text='Does the user need scholarship?')),
                ('university_type', models.CharField(choices=[('public', 'Public University'), ('private', 'Private University'), ('both', 'Both')], default='both', max_length=50)),
                ('campus_facilities', models.JSONField(blank=True, default=list, help_text='Preferred campus facilities (e.g., library, labs, sports, hostel)')),
                ('language_preference', models.CharField(choices=[('urdu', 'Urdu'), ('english', 'English'), ('both', 'Both')], default='both', max_length=50)),
                ('additional_requirements', models.TextField(blank=True, help_text='Any additional requirements or preferences')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(help_text='University name if not in database', max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('recommendation_reason', models.TextField(help_text='Why this university is recommended')),
                ('match_score', models.FloatField(default=0.0, help_text='Match score (0-100)')),
                ('achievements', models.TextField(blank=True, help_text='University achievements and highlights')),
                ('fee_information', models.TextField(blank=True, help_text='Fee structure information')),
                ('programs_available', models.JSONField(blank=True, default=list, help_text='Relevant programs available')),
                ('ai_analysis', models.TextField(blank=True, help_text='Detailed AI analysis')),
                ('pros', models.JSONField(blank=True, default=list, help_text='Pros of this university')),
                ('cons', models.JSONField(blank=True, default=list, help_text='Cons of this university')),
                ('rank', models.IntegerField(default=0, help_text='Ranking in the recommendation list')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='recommendations.university')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='recommendations.userprofile')),
            ],
            options={
                'ordering': ['rank', '-match_score'],
            },
        ),
    ]
