# Generated by Django 4.2.7 on 2025-12-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='current_gpa',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='intermediate_percentage',
            field=models.FloatField(blank=True, help_text='Percentage in Intermediate/FSC exams', null=True),
        ),
    ]
